Repository vyper-protocol/vyper-otc-ui, pull requests merged in 2022-09, with the labels that each got.

#20 Program interactions
  .gitignore
  models/OtcState.ts
  models/RateSwitchboardState.ts
  models/RedeemLogicForwardState.ts
  models/TxPackage.ts
  queries/generator.ts
  queries/otc-state/claim.ts
  queries/otc-state/deposit.ts
  queries/otc-state/fecthOtcState.ts
  queries/otc-state/settle.ts
  queries/otc-state/withdraw.ts
Labels: enhancement

#27 Added withdraw ix and otc state helper methods
  api/otc-state/withdraw.ts
  idls/vyper_otc.ts
  models/OtcState.ts
Labels: enhancement

#26 [19] Create basic nav routing
  components/organisms/TopBar/TopBar.tsx
  pages/contract/summary/[id].tsx
Labels: ui

#35 CoinGecko integration
  package.json
  yarn.lock
Labels: enhancement

#57 55 - Basic Create Contract page
  .prettierrc
  src/api/otc-state/create.ts
  src/api/switchboard/switchboardHelper.ts
  src/components/organisms/TopBar/TopBar.tsx
  src/configs/programs.json
  src/models/OtcInitializationParams.ts
  src/models/RateSwitchboardState.ts
  src/pages/contract/create/index.tsx
Labels: enhancement

#64 49 - add social links in top bar menu
  package.json
  src/components/atoms/Icon/Icon.tsx
  src/components/organisms/TopBar/TopBar.module.scss
  src/components/organisms/TopBar/TopBar.tsx
  src/configs/resources.json
  yarn.lock
Labels: enhancement, good first issue
